### ISSUE TITLE
Amazon DynamoDB Table migration project

### ISSUE THREAD

**Issue by tebanieo** [awslabs/amazon-dynamodb-tools#45]
### DynamoDB Migration project

We need a project that helps with the migration of DynamoDB tables. In the DynamoDB Documentation we have a guide on how to do it, but up to date there is no a project/tool that assist with this task, leaving users designing the solution on their own. 

The concept is very simple, migrate a DynamoDB table with near zero downtime. 

The project/solution/tool will:
- [x] Use CDK as it is easy to convert into a L3 construct that can be imported and re-used. 
- [x] Prefer serverless components.
- [x] Not interfere with the source DynamoDB table performance.
- [x] Only migrate the DynamoDB table data, and it will continue to replicate changes (Change Data Capture) to the destination.
- [x] Will have different stages of support for different request rates (throughput). 
- [x] Not loose CRUD operations, it is mandatory that 100% of the updates are processed.
- [x] Process the Updates in the same order as in the source table. 
- [x] Be eventual consistent (near-real time). 

Dear community feel free to add more requirements, or comments as you see fit. 

Thanks!
```[tasklist]
### Tasks
- [ ] Use CDK as it is easy to convert into an L3 construct that can be imported and re-used
- [ ] Prefer serverless components
- [ ] Avoid interference with the Source DynamoDB table performance
- [ ] Migrate table data only, continue to replicate CDC (Change data capture) to the destination
- [ ] Avoid loosing CRUD operations, 100% success rate.
- [ ] Process the updates in the same order than the source table.
- [ ] The solution is eventual consistent
- [ ] Add support for different throughput requirements
```

**Comment by terhunej** [comment]
.
